# Generated by Django 5.1.2 on 2024-12-04 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deckentry_location'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='decks.deck'),
            preserve_default=False,
        ),
    ]
