# Generated by Django 5.1.2 on 2024-12-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerprofile', '0001_initial'),
        ('tournament', '0003_remove_registration_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='playerprofile.player'),
            preserve_default=False,
        ),
    ]
