# Generated by Django 5.1.2 on 2024-12-04 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_registration_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tournament.tournament'),
            preserve_default=False,
        ),
    ]
