# Generated by Django 5.1.2 on 2024-12-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerprofile', '0001_initial'),
        ('tournament', '0006_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='DrawCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='MatchNum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='P1LoseCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='P1WinCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='P2LoseCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='P2WinCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='Player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Player2', to='playerprofile.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tournament.tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='Player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Player1', to='playerprofile.player'),
        ),
    ]
