# Generated by Django 5.1.2 on 2024-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_drawcount_match_matchnum_match_p1losecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
