# Generated by Django 5.1.3 on 2024-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0008_tournament_format_tournament_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("IN PROCESS", "In Process"),
                    ("COMPLETE", "Complete"),
                    ("CANCELLED", "Cancelled"),
                ],
                default=1,
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
