# Generated by Django 5.1.3 on 2024-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0009_tournament_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PIONEER", "Pioneer"),
                    ("MODERN", "Modern"),
                    ("PAUPER", "Pauper"),
                ],
                max_length=200,
            ),
        ),
    ]
