# Generated by Django 5.1.2 on 2024-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_tournament_current_match_alter_match_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
