# Generated by Django 5.1.2 on 2024-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_match_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='isDraw',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
