# Generated by Django 5.1.2 on 2024-12-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_match_isdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='MatchNum',
            new_name='RoundNum',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='current_match',
            new_name='current_round',
        ),
    ]
