# Generated by Django 5.1.2 on 2024-12-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_rename_matchnum_match_roundnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], max_length=200),
        ),
    ]
