# Generated by Django 5.1.3 on 2024-11-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField()),
                ("csv_file", models.FileField(upload_to="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "new"),
                            ("IN PROCESS", "In Process"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("error_msg", models.CharField(max_length=10000)),
                (
                    "type",
                    models.CharField(
                        choices=[("CARD", "Card"), ("DECK", "deck")], max_length=10
                    ),
                ),
            ],
        ),
    ]
