# Generated by Django 5.1.2 on 2024-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardImport', '0003_importrequest_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrequest',
            name='type',
            field=models.CharField(choices=[('CARD', 'Card'), ('DECK', 'Deck')], max_length=10),
        ),
    ]
