# Generated by Django 5.1.3 on 2024-11-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0003_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("PIONEER", "Pioneer"),
                            ("PAUPER", "Pauper"),
                            ("MODERN", "Modern"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeckEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rel_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cards.card"
                    ),
                ),
                (
                    "rel_deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="decks.deck"
                    ),
                ),
            ],
        ),
    ]
