# Generated by Django 5.1.2 on 2024-11-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_num',
            field=models.CharField(max_length=10),
        ),
    ]
