# Generated by Django 5.1.2 on 2024-11-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_set_code_alter_card_set_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(verbose_name='date published')),
                ('rel_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card')),
            ],
        ),
    ]
