# Generated by Django 5.1.2 on 2024-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_set_code_alter_card_set_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
